#!/usr/bin/env php
<?php
define('DEBUG', true);

if (substr(php_sapi_name(), 0, 3) === 'cgi')
{
	die("The cli tool is not supported when running php-cgi. It needs php-cli to function!\n\n");
}

require_once __DIR__ . '/vendor/autoload.php';

error_reporting(-1);
ini_set('display_errors', 1);

$app = require __DIR__. '/Core/bootstrap.php';

$console = new \QTCS\CLI\Console($app);

$console->run();

$console->show();